### ISSUE TITLE
A user in limbo in the Commuity Pages signup

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#366]
I received a note (below) via brca-exchange-contact@genomicsandhealth.org from a user who is having trouble registering on the community pages.  I went to the django admin interface at http://brcaexchange.org/backend/admin/, but could not find this user under All Users.  When I attempted to add this user myself, I got the message "This email address already exists".  What is going on?

From: soohwang.teo@cancerresearch.my

Dear officer in charge

I would like to register as a member of the BRCA exchange community, but it appears that my email is already on the database.  Could you please confirm whether this is the case and if yes, could you please reset the password?  thank you

Soo

Professor Dr Teo Soo Hwang PhD FASc
Head of Breast Cancer Research Programme
Cancer Research Malaysia

**Comment by zfisch** [comment]
Sure enough, seeing this when adding new users. From what I can surmise so far, there's a sync issue in the DB akin to http://stackoverflow.com/questions/11089850/integrityerror-duplicate-key-value-violates-unique-constraint-django-postgres.

Here's the error in the error log (which only shows when trying to add from the admin panel btw):

```[Sun Jan 22 17:42:14.050159 2017] [wsgi:error] [pid 60849:tid 140611382253312] ERROR | 01/22/2017 17:42:13 | base | 60849 | 140611382253312 | Internal Server Error: /backend/admin/users/proxyuser/add/
[Sun Jan 22 17:42:14.050183 2017] [wsgi:error] [pid 60849:tid 140611382253312] Traceback (most recent call last):
[Sun Jan 22 17:42:14.050186 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
[Sun Jan 22 17:42:14.050189 2017] [wsgi:error] [pid 60849:tid 140611382253312]     response = self.process_exception_by_middleware(e, request)
[Sun Jan 22 17:42:14.050200 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
[Sun Jan 22 17:42:14.050203 2017] [wsgi:error] [pid 60849:tid 140611382253312]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Jan 22 17:42:14.050206 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 541, in wrapper
[Sun Jan 22 17:42:14.050209 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return self.admin_site.admin_view(view)(*args, **kwargs)
[Sun Jan 22 17:42:14.050211 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
[Sun Jan 22 17:42:14.050214 2017] [wsgi:error] [pid 60849:tid 140611382253312]     response = view_func(request, *args, **kwargs)
[Sun Jan 22 17:42:14.050216 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
[Sun Jan 22 17:42:14.050219 2017] [wsgi:error] [pid 60849:tid 140611382253312]     response = view_func(request, *args, **kwargs)
[Sun Jan 22 17:42:14.050221 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 244, in inner
[Sun Jan 22 17:42:14.050224 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return view(request, *args, **kwargs)
[Sun Jan 22 17:42:14.050226 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1437, in add_view
[Sun Jan 22 17:42:14.050229 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return self.changeform_view(request, None, form_url, extra_context)
[Sun Jan 22 17:42:14.050231 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
[Sun Jan 22 17:42:14.050234 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return bound_func(*args, **kwargs)
[Sun Jan 22 17:42:14.050236 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
[Sun Jan 22 17:42:14.050239 2017] [wsgi:error] [pid 60849:tid 140611382253312]     response = view_func(request, *args, **kwargs)
[Sun Jan 22 17:42:14.050241 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
[Sun Jan 22 17:42:14.050244 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return func.__get__(self, type(self))(*args2, **kwargs2)
[Sun Jan 22 17:42:14.050246 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 184, in inner
[Sun Jan 22 17:42:14.050249 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return func(*args, **kwargs)
[Sun Jan 22 17:42:14.050251 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1378, in changeform_view
[Sun Jan 22 17:42:14.050254 2017] [wsgi:error] [pid 60849:tid 140611382253312]     self.save_model(request, new_object, form, not add)
[Sun Jan 22 17:42:14.050256 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 991, in save_model
[Sun Jan 22 17:42:14.050259 2017] [wsgi:error] [pid 60849:tid 140611382253312]     obj.save()
[Sun Jan 22 17:42:14.050261 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/base_user.py", line 74, in save
[Sun Jan 22 17:42:14.050263 2017] [wsgi:error] [pid 60849:tid 140611382253312]     super(AbstractBaseUser, self).save(*args, **kwargs)
[Sun Jan 22 17:42:14.050266 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 700, in save
[Sun Jan 22 17:42:14.050272 2017] [wsgi:error] [pid 60849:tid 140611382253312]     force_update=force_update, update_fields=update_fields)
[Sun Jan 22 17:42:14.050274 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 728, in save_base
[Sun Jan 22 17:42:14.050277 2017] [wsgi:error] [pid 60849:tid 140611382253312]     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
[Sun Jan 22 17:42:14.050279 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 812, in _save_table
[Sun Jan 22 17:42:14.050282 2017] [wsgi:error] [pid 60849:tid 140611382253312]     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[Sun Jan 22 17:42:14.050284 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 851, in _do_insert
[Sun Jan 22 17:42:14.050287 2017] [wsgi:error] [pid 60849:tid 140611382253312]     using=using, raw=raw)
[Sun Jan 22 17:42:14.050289 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 122, in manager_method
[Sun Jan 22 17:42:14.050292 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Sun Jan 22 17:42:14.050294 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1039, in _insert
[Sun Jan 22 17:42:14.050297 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return query.get_compiler(using=using).execute_sql(return_id)
[Sun Jan 22 17:42:14.050299 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
[Sun Jan 22 17:42:14.050318 2017] [wsgi:error] [pid 60849:tid 140611382253312]     cursor.execute(sql, params)
[Sun Jan 22 17:42:14.050320 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
[Sun Jan 22 17:42:14.050323 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return self.cursor.execute(sql, params)
[Sun Jan 22 17:42:14.050338 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
[Sun Jan 22 17:42:14.050340 2017] [wsgi:error] [pid 60849:tid 140611382253312]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Sun Jan 22 17:42:14.050342 2017] [wsgi:error] [pid 60849:tid 140611382253312]   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
[Sun Jan 22 17:42:14.050344 2017] [wsgi:error] [pid 60849:tid 140611382253312]     return self.cursor.execute(sql, params)
[Sun Jan 22 17:42:14.050346 2017] [wsgi:error] [pid 60849:tid 140611382253312] IntegrityError: duplicate key value violates unique constraint "users_myuser_pkey"
[Sun Jan 22 17:42:14.050348 2017] [wsgi:error] [pid 60849:tid 140611382253312] DETAIL:  Key (id)=(118) already exists.```

**Comment by zfisch** [comment]
looks like all signups are broken at the moment (not only for this user), working on a fix

**Comment by zfisch** [comment]
this is resolved now -- required resyncing primary keys for users_myuser table as described above

**Comment by melissacline** [comment]
Thanks, Zack!

**Comment by zfisch** [comment]
shoutout to @strbean too for working through this one with me!

we can make a hotfix to the email list signup bug too if it's important to get out before our next code deployment.
